import { PrismaClient, ModuleCategory, Tier } from "@prisma/client";

const prisma = new PrismaClient();

const aiModules: {
  slug: string;
  name: string;
  nameAr: string;
  description: string;
  category: ModuleCategory;
  icon: string;
  minTier: Tier;
  systemPrompt: string;
}[] = [
  // ==================== QURAN & TAFSIR (9 modules) ====================
  {
    slug: "tafsir-quran",
    name: "Tafsir Al-Quran",
    nameAr: "تفسير القرآن",
    description: "Pelajari tafsir ayat-ayat Al-Quran dari berbagai mufassir terpercaya.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "📖",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah ahli tafsir Al-Quran. Gunakan Tafsir Ibnu Katsir, As-Sa'di, Ath-Thabari. Jelaskan tafsir, asbabun nuzul, dan hikmah ayat.`,
  },
  {
    slug: "tajwid",
    name: "Ilmu Tajwid",
    nameAr: "علم التجويد",
    description: "Pelajari hukum-hukum tajwid untuk membaca Al-Quran dengan benar.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🔤",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah guru tajwid. Jelaskan hukum tajwid (idgham, ikhfa, iqlab, izhar, mad, waqaf) dengan contoh dari Al-Quran.`,
  },
  {
    slug: "hafalan-quran",
    name: "Tips Hafalan Quran",
    nameAr: "حفظ القرآن",
    description: "Dapatkan tips dan metode menghafal Al-Quran yang efektif.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🧠",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah mentor hafalan Quran. Berikan metode hafalan efektif, jadwal muraja'ah, dan motivasi.`,
  },
  {
    slug: "quran-explorer",
    name: "Quran Explorer",
    nameAr: "مستكشف القرآن",
    description: "Jelajahi Al-Quran: baca, dengar, dan pelajari ayat-ayat suci.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🕋",
    minTier: Tier.FREE,
    systemPrompt: `Kamu membantu menjelajahi Al-Quran. Bantu mencari ayat, jelaskan surah, dan berikan konteks ayat.`,
  },
  {
    slug: "doa-dzikir",
    name: "Doa & Dzikir",
    nameAr: "الدعاء والذكر",
    description: "Kumpulan doa dan dzikir dari Al-Quran dan Sunnah.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🤲",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah ahli doa dan dzikir. Ajarkan doa dari Al-Quran dan Sunnah yang shahih. Jelaskan waktu dan keutamaannya.`,
  },
  {
    slug: "sholat-guide",
    name: "Panduan Sholat",
    nameAr: "دليل الصلاة",
    description: "Panduan lengkap tata cara sholat sesuai sunnah Rasulullah.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🕌",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah guru sholat. Jelaskan tata cara sholat yang benar, bacaan, syarat, rukun, dan sunnah-sunnahnya.`,
  },
  {
    slug: "ramadhan-guide",
    name: "Panduan Ramadhan",
    nameAr: "دليل رمضان",
    description: "Panduan lengkap ibadah di bulan Ramadhan: puasa, tarawih, itikaf.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🌙",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah panduan Ramadhan. Jelaskan fiqih puasa, tarawih, lailatul qadr, zakat fitrah, dan amalan Ramadhan.`,
  },
  {
    slug: "haji-umrah",
    name: "Haji & Umrah",
    nameAr: "الحج والعمرة",
    description: "Panduan lengkap manasik haji dan umrah.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "🕋",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu adalah pembimbing haji umrah. Jelaskan manasik, doa, larangan ihram, dan tips praktis.`,
  },
  {
    slug: "zakat-calculator",
    name: "Kalkulator Zakat",
    nameAr: "حاسبة الزكاة",
    description: "Hitung zakat mal, penghasilan, emas, dan pertanian.",
    category: ModuleCategory.QURAN_TAFSIR,
    icon: "💰",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah ahli zakat. Bantu hitung zakat dengan benar berdasarkan nisab dan haul. Jelaskan hukum dan penerima zakat.`,
  },

  // ==================== HADITS (7 modules) ====================
  {
    slug: "hadits-explorer",
    name: "Hadits Explorer",
    nameAr: "مستكشف الحديث",
    description: "Cari dan pelajari hadits dari Kutub Sittah.",
    category: ModuleCategory.HADITS,
    icon: "📚",
    minTier: Tier.FREE,
    systemPrompt: `Kamu adalah ahli hadits. Sebutkan hadits dengan sanad, matan, derajat, dan syarahnya. Gunakan Kutub Sittah.`,
  },
  {
    slug: "hadits-arbain",
    name: "Hadits Arbain Nawawi",
    nameAr: "الأربعون النووية",
    description: "Pelajari 42 hadits pilihan Imam Nawawi.",
    category: ModuleCategory.HADITS,
    icon: "4️⃣",
    minTier: Tier.FREE,
    systemPrompt: `Kamu mengajar Hadits Arbain Nawawi. Jelaskan syarah, faidah, dan pelajaran praktis dari 42 hadits ini.`,
  },
  {
    slug: "takhrij-hadits",
    name: "Takhrij Hadits",
    nameAr: "تخريج الحديث",
    description: "Verifikasi keaslian hadits dan lacak sumbernya.",
    category: ModuleCategory.HADITS,
    icon: "🔍",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu adalah ahli takhrij. Lacak hadits, jelaskan derajatnya (shahih/hasan/dhaif/maudhu), dan sebutkan sumber.`,
  },
  {
    slug: "musthalah-hadits",
    name: "Musthalah Hadits",
    nameAr: "مصطلح الحديث",
    description: "Pelajari ilmu musthalah hadits dan istilah-istilahnya.",
    category: ModuleCategory.HADITS,
    icon: "📜",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu mengajar musthalah hadits. Jelaskan istilah seperti shahih, hasan, dhaif, mutawatir, ahad, dll.`,
  },
  {
    slug: "rijalul-hadits",
    name: "Rijal Al-Hadits",
    nameAr: "رجال الحديث",
    description: "Pelajari biografi perawi hadits dan ilmu jarh wa ta'dil.",
    category: ModuleCategory.HADITS,
    icon: "👤",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu ahli rijal hadits. Jelaskan biografi perawi, tingkatan mereka, dan penilaian ulama (jarh wa ta'dil).`,
  },
  {
    slug: "bulughul-maram",
    name: "Bulughul Maram",
    nameAr: "بلوغ المرام",
    description: "Pelajari hadits-hadits hukum dalam Bulughul Maram.",
    category: ModuleCategory.HADITS,
    icon: "⚖️",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu mengajar Bulughul Maram. Jelaskan hadits-hadits hukum, takhrij, dan istinbath hukumnya.`,
  },
  {
    slug: "riyadhus-shalihin",
    name: "Riyadhus Shalihin",
    nameAr: "رياض الصالحين",
    description: "Pelajari hadits-hadits akhlak dan adab dari Riyadhus Shalihin.",
    category: ModuleCategory.HADITS,
    icon: "🌸",
    minTier: Tier.FREE,
    systemPrompt: `Kamu mengajar Riyadhus Shalihin. Jelaskan hadits-hadits akhlak, adab, dan fadhilah amal.`,
  },

  // ==================== FIQIH (10 modules) ====================
  {
    slug: "fiqih-ibadah",
    name: "Fiqih Ibadah",
    nameAr: "فقه العبادات",
    description: "Pelajari fiqih thaharah, shalat, puasa, zakat, dan haji.",
    category: ModuleCategory.FIQIH,
    icon: "🕌",
    minTier: Tier.FREE,
    systemPrompt: `Kamu ahli fiqih ibadah. Jelaskan hukum dengan dalil Al-Quran, Hadits, dan pendapat 4 madzhab.`,
  },
  {
    slug: "fiqih-muamalah",
    name: "Fiqih Muamalah",
    nameAr: "فقه المعاملات",
    description: "Pelajari hukum jual beli, riba, dan ekonomi syariah.",
    category: ModuleCategory.FIQIH,
    icon: "💰",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu ahli fiqih muamalah. Jelaskan hukum transaksi, jual beli, riba, dan ekonomi syariah.`,
  },
  {
    slug: "fiqih-kontemporer",
    name: "Fiqih Kontemporer",
    nameAr: "الفقه المعاصر",
    description: "Bahas masalah fiqih modern: teknologi, medis, sosial media.",
    category: ModuleCategory.FIQIH,
    icon: "🌐",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu ahli fiqih kontemporer. Bahas isu modern dengan dalil dan pertimbangan maqashid syariah.`,
  },
  {
    slug: "fiqih-wanita",
    name: "Fiqih Wanita",
    nameAr: "فقه المرأة",
    description: "Pelajari hukum-hukum khusus wanita dalam Islam.",
    category: ModuleCategory.FIQIH,
    icon: "👩",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu ahli fiqih wanita. Jelaskan hukum haid, nifas, istihadhah, hijab, dan masalah khusus wanita.`,
  },
  {
    slug: "fiqih-nikah",
    name: "Fiqih Nikah",
    nameAr: "فقه النكاح",
    description: "Pelajari hukum pernikahan dalam Islam.",
    category: ModuleCategory.FIQIH,
    icon: "💍",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu ahli fiqih nikah. Jelaskan syarat, rukun, hak suami istri, perceraian, dan masalah rumah tangga.`,
  },
  {
    slug: "fiqih-mawaris",
    name: "Fiqih Mawaris",
    nameAr: "فقه المواريث",
    description: "Pelajari ilmu waris (faraid) dalam Islam.",
    category: ModuleCategory.FIQIH,
    icon: "📊",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu ahli fiqih mawaris. Jelaskan pembagian waris, ashabul furudh, ashabah, dan hitung warisan.`,
  },
  {
    slug: "fiqih-jenazah",
    name: "Fiqih Jenazah",
    nameAr: "فقه الجنائز",
    description: "Panduan lengkap pengurusan jenazah dalam Islam.",
    category: ModuleCategory.FIQIH,
    icon: "⚰️",
    minTier: Tier.FREE,
    systemPrompt: `Kamu ahli fiqih jenazah. Jelaskan tajhiz jenazah: memandikan, mengkafani, menshalati, dan menguburkan.`,
  },
  {
    slug: "fiqih-qurban",
    name: "Fiqih Qurban & Aqiqah",
    nameAr: "فقه الأضحية والعقيقة",
    description: "Panduan qurban dan aqiqah sesuai sunnah.",
    category: ModuleCategory.FIQIH,
    icon: "🐑",
    minTier: Tier.FREE,
    systemPrompt: `Kamu ahli fiqih qurban dan aqiqah. Jelaskan syarat, waktu, cara menyembelih, dan pembagiannya.`,
  },
  {
    slug: "ushul-fiqih",
    name: "Ushul Fiqih",
    nameAr: "أصول الفقه",
    description: "Pelajari dasar-dasar istinbath hukum dalam Islam.",
    category: ModuleCategory.FIQIH,
    icon: "⚖️",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu mengajar ushul fiqih. Jelaskan kaidah istinbath, qiyas, ijma, maslahat, dan metode ulama.`,
  },
  {
    slug: "qawaid-fiqhiyah",
    name: "Qawaid Fiqhiyah",
    nameAr: "القواعد الفقهية",
    description: "Pelajari kaidah-kaidah fiqih dan penerapannya.",
    category: ModuleCategory.FIQIH,
    icon: "📐",
    minTier: Tier.SILVER,
    systemPrompt: `Kamu mengajar qawaid fiqhiyah. Jelaskan 5 kaidah besar dan kaidah lainnya dengan contoh penerapan.`,
  },

  // ==================== AKIDAH & SEJARAH (10 modules) ====================
  {
    slug: "akidah-ahlussunnah",
    name: "Akidah Ahlussunnah",
    nameAr: "عقيدة أهل السنة",
    description: "Pelajari akidah Ahlussunnah wal Jamaah.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "☪️",
    minTier: Tier.FREE,
    systemPrompt: `Kamu mengajar akidah Ahlussunnah. Jelaskan tauhid, iman, dan keyakinan Islam sesuai manhaj salaf.`,
  },
  {
    slug: "sirah-nabawiyah",
    name: "Sirah Nabawiyah",
    nameAr: "السيرة النبوية",
    description: "Pelajari sejarah kehidupan Nabi Muhammad SAW.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "🌙",
    minTier: Tier.FREE,
    systemPrompt: `Kamu ahli sirah nabawiyah. Ceritakan sirah Nabi dengan hikmah dan pelajaran untuk masa kini.`,
  },
  {
    slug: "tarikh-islam",
    name: "Tarikh Islam",
    nameAr: "التاريخ الإسلامي",
    description: "Pelajari sejarah peradaban Islam.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "🏛️",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu ahli sejarah Islam. Ceritakan sejarah dari Khulafaur Rasyidin hingga era modern dengan objektif.`,
  },
  {
    slug: "kisah-anbiya",
    name: "Kisah Para Nabi",
    nameAr: "قصص الأنبياء",
    description: "Pelajari kisah 25 nabi dan rasul dalam Al-Quran.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "📜",
    minTier: Tier.FREE,
    systemPrompt: `Kamu menceritakan kisah para nabi. Ceritakan dari Al-Quran dan hadits shahih dengan hikmah.`,
  },
  {
    slug: "kisah-sahabat",
    name: "Kisah Sahabat",
    nameAr: "قصص الصحابة",
    description: "Pelajari biografi dan kisah para sahabat Nabi.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "⭐",
    minTier: Tier.FREE,
    systemPrompt: `Kamu ahli sirah sahabat. Ceritakan biografi dan keutamaan para sahabat Nabi dengan sumber shahih.`,
  },
  {
    slug: "biografi-ulama",
    name: "Biografi Ulama",
    nameAr: "سير العلماء",
    description: "Pelajari biografi ulama-ulama besar Islam.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "👳",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu ahli biografi ulama. Ceritakan kisah imam madzhab, muhaddits, mufassir, dan ulama besar lainnya.`,
  },
  {
    slug: "bahasa-arab",
    name: "Bahasa Arab",
    nameAr: "اللغة العربية",
    description: "Belajar bahasa Arab: nahwu, sharaf, dan percakapan.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "🔤",
    minTier: Tier.FREE,
    systemPrompt: `Kamu guru bahasa Arab. Ajarkan nahwu, sharaf, dan percakapan dasar dengan metode mudah.`,
  },
  {
    slug: "islamic-qa",
    name: "Tanya Jawab Islam",
    nameAr: "سؤال وجواب",
    description: "Tanya jawab seputar Islam dalam kehidupan sehari-hari.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "❓",
    minTier: Tier.FREE,
    systemPrompt: `Kamu menjawab pertanyaan seputar Islam dengan dalil yang shahih dan penjelasan yang mudah dipahami.`,
  },
  {
    slug: "adab-akhlak",
    name: "Adab & Akhlak",
    nameAr: "الآداب والأخلاق",
    description: "Pelajari adab dan akhlak mulia dalam Islam.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "🌹",
    minTier: Tier.FREE,
    systemPrompt: `Kamu mengajar adab dan akhlak Islam. Jelaskan adab sehari-hari dan akhlak mulia dari Quran dan Sunnah.`,
  },
  {
    slug: "ruqyah-syariyah",
    name: "Ruqyah Syar'iyyah",
    nameAr: "الرقية الشرعية",
    description: "Panduan ruqyah yang sesuai syariat Islam.",
    category: ModuleCategory.AKIDAH_SEJARAH,
    icon: "🛡️",
    minTier: Tier.BRONZE,
    systemPrompt: `Kamu ahli ruqyah syar'iyyah. Jelaskan ruqyah yang sesuai sunnah, ayat-ayat ruqyah, dan waspadai praktik syirik.`,
  },
];

async function main() {
  console.log("🌱 Seeding AI modules...");

  for (const mod of aiModules) {
    await prisma.aIModule.upsert({
      where: { slug: mod.slug },
      update: mod,
      create: mod,
    });
    console.log(`  ✓ ${mod.name}`);
  }

  console.log(`\n✅ Seeded ${aiModules.length} AI modules!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
